--Plugins init
require("core.plugins-config.treesitter")
require("core.plugins-config.telescope")
require("core.plugins-config.nvim-cmp")
require("core.plugins-config.lsp-config")
require("core.plugins-config.lualine")
require("core.plugins-config.nvim-tree")
require("core.plugins-config.colorizer")
require("core.plugins-config.theme")
require("core.plugins-config.vimtex")
require("core.plugins-config.autopair")
require("core.plugins-config.null-ls")
require("core.plugins-config.dap")
require("core.plugins-config.gitblame")
require("core.plugins-config.ibl")
require("core.plugins-config.illuminate")
